# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - VKMCompassAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        env:
          # Provide a connection string for tests from GitHub Secrets
          # Create a repository secret named TEST_CONNECTION_STRING with your DB connection
          TEST_CONNECTION_STRING: ${{ secrets.TEST_CONNECTION_STRING }}
          # Map the secret to the env var the app expects
          MONGODB_URI: ${{ secrets.TEST_CONNECTION_STRING }}
        run: |
          npm install
          npm run build --if-present
          npm run test:e2e --if-present || true
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7D9493B7967B4FA4A63A9B8B100D954A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E335FC34EDB4E49971DB3031D63ABB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B08DB1EEA9C843ACA7D3201178E7024E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VKMCompassAPI'
          slot-name: 'Production'
          package: .
        env:
          # Also pass the connection string to the deployment action if needed at deploy time
          CONNECTION_STRING: ${{ secrets.TEST_CONNECTION_STRING }}
          # Make the same secret available as MONGODB_URI for the running app if needed
          MONGODB_URI: ${{ secrets.TEST_CONNECTION_STRING }}
          